### ISSUE TITLE
UI not responsive when fullscreen

### ISSUE THREAD

**Issue by krrishg** [anuragregmi/remainder#2]
The UI is not updated according to the size of window.
![screenshot from 2018-03-23 09-13-01](https://user-images.githubusercontent.com/17355332/37810108-87cddfd8-2e7a-11e8-9a80-17acbcda445e.png)

**Comment by anuragregmi** [comment]
Fixed  [here](https://github.com/anuragregmi/remainder/tree/969760bd939b17dbdf3a6ec83e2d913280dcb6e2)
